language: node_js

node_js:
  - 'node'

addons:
  code_climate:
    repo_token: b04bcf6ebc70567672c834d14acc6eab1ddb5b2fe1cfa62d9d1d421010a0ce31

services:
  - xvfb

install:
  - npm install
  - npm install codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
